#!/usr/bin/env bash
# Generated by claude-tweaks /init (Step 14 — Cloud/Routine Parity Setup).
# Regenerated in full on every /init run from .claude/settings.json — do not hand-edit;
# customize by changing enabledPlugins/extraKnownMarketplaces instead, then re-run /init.
# Idempotent: safe to run on every cloud session, not just the first.
#
# Paste this canonical line into this project's claude.ai/code environment Setup script
# field (environment settings, web UI only — no API sets this remotely) so cloud sessions
# get the same plugins available locally:
#   { bash scripts/claude-cloud-setup.sh || bash */scripts/claude-cloud-setup.sh; } > "$HOME/claude-cloud-setup.log" 2>&1 || true
# See CLAUDE.md's "Cloud parity" section for why this exists and what it doesn't cover.
set -euo pipefail

# The Setup script field's cwd is a workspace root containing the cloned repo as a single
# subdirectory, not the repo root itself ($HOME is not a reliable substitute either) —
# locate the repo by its .git marker (directory or file, to also cover gitdir-file clone
# forms) and cd into it before anything below runs. This defense and the field line's own
# `*/scripts/` fallback both encode the same workspace-root layout assumption — changing
# one obliges re-verifying the other.
SEARCH_ROOT="$(pwd)"
REPO_DIR=$(find "$SEARCH_ROOT" -maxdepth 2 \( -type d -o -type f \) -name .git 2>/dev/null | head -1 | xargs -I{} dirname {})
[ -n "$REPO_DIR" ] && cd "$REPO_DIR"

# Marketplaces referenced below that Claude Code doesn't already know by name — refreshed
# every run so a later `update` pulls from a current catalog pointer, not a stale local clone.
# `add` stays best-effort (a duplicate add is the expected no-op on every re-run), but a
# failed `update` is announced rather than swallowed: `claude plugin update` decides whether
# a plugin is current by comparing version strings against THIS local catalog and nothing
# else, so a catalog that failed to refresh makes every "already at the latest version"
# below true of a stale snapshot and false of reality.
claude plugin marketplace add thomasholknielsen/claude-tweaks-marketplace 2>/dev/null || true
claude plugin marketplace update claude-tweaks-marketplace \
  || echo "[claude-cloud-setup] WARNING: catalog refresh failed for claude-tweaks-marketplace — version checks below are measured against whatever catalog this sandbox already had."
# `claude-plugins-official` (Anthropic's own marketplace) still needs an explicit `add` here:
# on a fresh cloud sandbox it is not pre-registered at the CLI/runtime level (only this
# project's own .claude/settings.json schema recognizes it by name with no settings entry),
# so `update` alone is a silent no-op until `add` has run at least once in this sandbox.
claude plugin marketplace add anthropics/claude-plugins-official 2>/dev/null || true
claude plugin marketplace update claude-plugins-official \
  || echo "[claude-cloud-setup] WARNING: catalog refresh failed for claude-plugins-official — version checks below are measured against whatever catalog this sandbox already had."
claude plugin marketplace add pbakaus/impeccable 2>/dev/null || true
claude plugin marketplace update impeccable \
  || echo "[claude-cloud-setup] WARNING: catalog refresh failed for impeccable — version checks below are measured against whatever catalog this sandbox already had."

# Plugins declared in .claude/settings.json#enabledPlugins. `claude plugin install` is NOT
# idempotent (errors if the plugin is already present), so try update first and fall back to
# install if update fails. This avoids fragile JSON parsing and works reliably across all runs.
# Deliberately not silencing update's stderr here: if update fails for a real reason (network,
# corrupt marketplace cache) rather than "not installed yet," the install fallback's own
# "already installed" error would otherwise be the only, misleading diagnostic surfaced.
PLUGIN_SPECS="claude-tweaks@claude-tweaks-marketplace superpowers@claude-plugins-official code-simplifier@claude-plugins-official impeccable@impeccable"
for spec in $PLUGIN_SPECS; do
  claude plugin update "$spec" --scope project || claude plugin install "$spec" --scope project
done

# Verify what landed; do not trust that the loop above landed it. `claude plugin update`
# compares version strings and never looks inside the cached plugin directory — a sandbox
# whose plugin directory is older than its own installation record passes the loop with
# "already at the latest version" and exit 0, which is indistinguishable from success
# (claude-tweaks #129: a Routine ran a build predating a shipped fix for days, reporting the
# pre-fix behavior as though it were current). Resolve each plugin's version from the
# directory a session would actually load, compare it against the catalog, and repair drift.
claude plugin list --json > /tmp/cc-installed.json 2>/dev/null || echo '[]' > /tmp/cc-installed.json
claude plugin marketplace list --json > /tmp/cc-marketplaces.json 2>/dev/null || echo '[]' > /tmp/cc-marketplaces.json

for spec in $PLUGIN_SPECS; do
  VERDICT=$(node -e '
    const fs = require("fs");
    const spec = process.argv[1];
    const [pluginName, marketplaceName] = spec.split("@");
    const read = (p) => { try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return null; } };

    // The installed directory decides what a session loads. `claude plugin list`s own
    // `version` is metadata recorded beside that directory rather than read out of it, and
    // `installed_plugins.json`s `gitCommitSha` is not refreshed by `claude plugin update`
    // at all — neither can be trusted to describe the files actually on disk.
    const entry = (read("/tmp/cc-installed.json") || []).find((p) => p.id === spec);
    const manifest = entry && read(entry.installPath + "/.claude-plugin/plugin.json");
    const installed = (manifest && manifest.version) || "none";

    const mkt = (read("/tmp/cc-marketplaces.json") || []).find((m) => m.name === marketplaceName);
    const catalog = mkt && read(mkt.installLocation + "/.claude-plugin/marketplace.json");
    const declared = catalog && (catalog.plugins || []).find((p) => p.name === pluginName);
    // Not every marketplace declares a per-plugin version (claude-plugins-official does not).
    // An absent declaration is nothing to compare against, not evidence of drift — but that
    // guard must not also swallow a total non-install. On a cold sandbox, the marketplace
    // list/read above can fail for the same underlying reason nothing got installed (first-run
    // race, marketplace not yet resolvable), which degrades `expected` to "unversioned" too —
    // indistinguishable, by this variable alone, from a marketplace that legitimately has no
    // version field. `installed === "none"` is unambiguous either way and must win.
    let expected = (declared && declared.version) || null;
    // A git-subdir-sourced entry (claude-tweaks, post-#418) carries no entry-level version at
    // all: the payload plugin.json is the single version authority, and the catalog only pins
    // a release commit sha. Resolve that sha to a version by reading the manifest the source
    // repo actually shipped at that commit, instead of treating a missing version field as
    // nothing to compare (claude-tweaks #860, which used to make claude-tweaks drift permanently
    // unverifiable via this comparison).
    if (!expected && declared && declared.source && declared.source.source === "git-subdir" && declared.source.sha && declared.source.url) {
      try {
        const rawBase = declared.source.url.replace(/^https:\/\/github\.com\//, "https://raw.githubusercontent.com/");
        const rawUrl = rawBase + "/" + declared.source.sha + "/" + declared.source.path + "/.claude-plugin/plugin.json";
        const atSha = JSON.parse(require("child_process").execSync("curl -fsSL " + JSON.stringify(rawUrl), { encoding: "utf8", timeout: 10000 }));
        if (atSha && atSha.version) expected = atSha.version;
      } catch {
        // Network failure, missing manifest at that path, or unexpected shape: fall through to
        // "unversioned" below, the same fail-open posture as an unresolvable catalog entry.
      }
    }
    expected = expected || "unversioned";

    const drift = installed === "none" || (expected !== "unversioned" && installed !== expected);
    console.log([installed, expected, drift ? "DRIFT" : "ok", (entry && entry.installPath) || "-"].join("\t"));
  ' "$spec" || true)
  # `|| true` inside the substitution, because this loop is diagnostic-and-repair, not a
  # prerequisite: under `set -e` an unreadable manifest would otherwise abort the script
  # here and take the agent-browser/Chrome install below down with it.
  if [ -z "$VERDICT" ]; then
    echo "[claude-cloud-setup] WARNING: could not resolve an installed version for $spec — freshness unverified."
    continue
  fi

  INSTALLED=$(printf '%s' "$VERDICT" | cut -f1)
  EXPECTED=$(printf '%s' "$VERDICT" | cut -f2)
  STATUS=$(printf '%s' "$VERDICT" | cut -f3)
  WHERE=$(printf '%s' "$VERDICT" | cut -f4)
  echo "[claude-cloud-setup] $spec: installed=$INSTALLED catalog=$EXPECTED ($STATUS) at $WHERE"

  if [ "$STATUS" = "DRIFT" ]; then
    echo "[claude-cloud-setup] DRIFT: $spec resolves v$INSTALLED but the catalog declares v$EXPECTED — reinstalling."
    claude plugin uninstall "$spec" --scope project || true
    claude plugin install "$spec" --scope project
  fi
done

# agent-browser — required in the cloud sandbox for /browse-dependent skills
# (/stories, /visual-review, /review, qa-agent, /flow) to work in cloud sessions.
npm install -g agent-browser

# Chrome, so agent-browser can actually launch a browser (the CLI alone can't render a
# page). Unmodified `agent-browser install --with-deps` doesn't work in a cloud sandbox:
#  - it shells out to `sudo apt-get ...` for Chrome's runtime libraries; cloud sandboxes
#    commonly run this whole script as root with no `sudo` binary at all, so that call
#    fails silently and Chrome downloads but can't launch (missing shared libs) — install
#    the libraries directly instead, with no `sudo` prefix.
#  - its own Chrome download can fail `invalid peer certificate: UnknownIssuer` behind a
#    TLS-inspecting sandbox proxy (its bundled HTTP client doesn't trust the sandbox's CA
#    store) — fetch Chrome for Testing directly via `curl` instead, which honors the
#    system CA store, and place it where agent-browser's own cache expects it.
CHROME_LIBS="libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
  libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 \
  libpango-1.0-0 libcairo2 libatspi2.0-0 libxshmfence1"
# Populate the local apt cache BEFORE resolving package names against it — a fresh
# sandbox's cache is empty until `update` runs, which would otherwise make every
# `apt-cache policy` lookup below (including the t64 fallback) report no candidate.
apt-get update -qq
RESOLVED_LIBS=""
for pkg in $CHROME_LIBS; do
  # Capture apt-cache policy's own output into a variable first, rather than piping it
  # straight into `grep -q` — under this script's `set -o pipefail`, `grep -q` closing its
  # stdin the instant it finds a match can SIGPIPE the still-writing producer, and
  # pipefail then reports that SIGPIPE (141) as the pipeline's exit status instead of
  # grep's real success: a false negative on a genuine match.
  POLICY_OUT="$(apt-cache policy "$pkg" 2>/dev/null || true)"
  if echo "$POLICY_OUT" | grep -qE "Candidate: [^(]"; then
    RESOLVED_LIBS="$RESOLVED_LIBS $pkg"
  else
    # The sandbox's Debian base may have undergone the 64-bit time_t transition, which
    # renamed some packages with a `t64` suffix (e.g. libasound2 -> libasound2t64).
    POLICY_OUT_T64="$(apt-cache policy "${pkg}t64" 2>/dev/null || true)"
    if echo "$POLICY_OUT_T64" | grep -qE "Candidate: [^(]"; then
      RESOLVED_LIBS="$RESOLVED_LIBS ${pkg}t64"
    fi
  fi
done
# $RESOLVED_LIBS is an intentionally unquoted, space-separated word list. `unzip` isn't
# subject to the t64 rename dance (its package name doesn't vary) but a minimal sandbox
# image may not ship it, and the Chrome-for-Testing zip below needs it.
apt-get install -y -qq unzip $RESOLVED_LIBS

AB_BROWSERS_DIR="${HOME}/.agent-browser/browsers"
mkdir -p "$AB_BROWSERS_DIR"
CFT_JSON="$(curl -fsSL https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)"
read -r CHROME_VERSION CHROME_URL <<<"$(echo "$CFT_JSON" | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{const j=JSON.parse(d);const s=j.channels.Stable;console.log(s.version, s.downloads.chrome.find(x=>x.platform==='linux64').url)})")"
CHROME_DIR="${AB_BROWSERS_DIR}/chrome-${CHROME_VERSION}"
if [ ! -d "$CHROME_DIR" ]; then
  mkdir -p "$CHROME_DIR"
  curl -fsSL "$CHROME_URL" -o /tmp/chrome-for-testing.zip
  unzip -q -o /tmp/chrome-for-testing.zip -d "$CHROME_DIR"
  rm -f /tmp/chrome-for-testing.zip
fi
chmod +x "${CHROME_DIR}/chrome-linux64/chrome"
